import type { ProjectFile } from '@/types';
import { getFileType } from '@/services/fileSystem';

function makeFile(path: string, content: string, index: number): ProjectFile {
  return {
    id: `starter_${index}_${path.replace(/[^\w.-]+/g, '_')}`,
    path,
    content,
    type: getFileType(path),
  };
}

export function createReactViteStarterFiles(projectName = 'Joyful App'): ProjectFile[] {
  const safePackageName = projectName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48) || 'joyful-app';

  const files = [
    {
      path: 'package.json',
      content: JSON.stringify({
        name: safePackageName,
        private: true,
        version: '0.1.0',
        type: 'module',
        scripts: {
          dev: 'vite --host 0.0.0.0',
          build: 'vite build',
          preview: 'vite preview --host 0.0.0.0',
        },
        dependencies: {
          '@vitejs/plugin-react': 'latest',
          vite: 'latest',
          react: 'latest',
          'react-dom': 'latest',
          'lucide-react': 'latest',
        },
        devDependencies: {},
      }, null, 2),
    },
    {
      path: 'index.html',
      content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`,
    },
    {
      path: 'src/main.jsx',
      content: `import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App.jsx';
import './styles.css';

createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`,
    },
    {
      path: 'src/App.jsx',
      content: `export default function App() {
  return (
    <main className="app-shell">
      <section className="hero">
        <p className="eyebrow">React/Vite starter</p>
        <h1>${projectName}</h1>
        <p>
          This project is ready to preview, edit, and hand to Joyful AI for the
          next build step.
        </p>
        <div className="actions">
          <button type="button">Start building</button>
          <span>Framework, config, and preview entry are already wired.</span>
        </div>
      </section>
    </main>
  );
}`,
    },
    {
      path: 'src/styles.css',
      content: `:root {
  color-scheme: light;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  color: #172033;
  background: #f5f7fb;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-width: 320px;
  min-height: 100vh;
  background:
    radial-gradient(circle at 20% 20%, rgba(47, 91, 255, 0.14), transparent 28rem),
    linear-gradient(135deg, #f8fafc 0%, #eef2ff 46%, #fff7ed 100%);
}

button {
  border: 0;
  border-radius: 8px;
  background: #2f5bff;
  color: #ffffff;
  cursor: pointer;
  font: inherit;
  font-weight: 800;
  padding: 0.85rem 1rem;
}

button:hover {
  background: #2348d8;
}

.app-shell {
  min-height: 100vh;
  display: grid;
  place-items: center;
  padding: clamp(1rem, 4vw, 3rem);
}

.hero {
  width: min(760px, 100%);
  border: 1px solid rgba(23, 32, 51, 0.1);
  border-radius: 8px;
  background: rgba(255, 255, 255, 0.86);
  box-shadow: 0 24px 80px rgba(23, 32, 51, 0.12);
  padding: clamp(1.5rem, 5vw, 3rem);
}

.eyebrow {
  margin: 0 0 0.75rem;
  color: #f23c78;
  font-size: 0.76rem;
  font-weight: 900;
  letter-spacing: 0;
  text-transform: uppercase;
}

h1 {
  margin: 0;
  font-size: clamp(2.4rem, 8vw, 5rem);
  line-height: 0.95;
}

.hero p:not(.eyebrow) {
  max-width: 620px;
  color: #5d6475;
  font-size: 1.05rem;
  line-height: 1.7;
}

.actions {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 1rem;
  margin-top: 1.5rem;
}

.actions span {
  color: #6f7788;
  font-size: 0.9rem;
}`,
    },
    {
      path: 'vite.config.js',
      content: `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    host: '0.0.0.0',
  },
});`,
    },
    {
      path: 'README.md',
      content: `# ${projectName}

React/Vite starter generated by Joyful.

- Run \`npm run dev\` for local development.
- Edit \`src/App.jsx\` and \`src/styles.css\` to change the app.
- The Joyful preview uses the same React entry and styles.
`,
    },
  ];

  return files.map((file, index) => makeFile(file.path, file.content, index));
}
