export interface Chunk {
  written?: string[]
  files: File[]
  paths: string[]
}

export interface File {
  path: string
  content: string
}

export async function* getContents({
  messages,
  modelId,
  paths,
}: {
  messages: any[]
  modelId: string
  paths: string[]
}): AsyncGenerator<Chunk> {
  const files: File[] = paths.map((path) => ({
    path,
    content: `// File: ${path}\n// Generated by Joyful AI\n\nexport const name = '${path.split('/').pop()}';\n`,
  }))
  yield { files, paths }
}
